test: check pkglock is updated correctly
larsgw/cli pull request #1
Opened 2018-10-29 14:43 UTC by feelepxyz

@larsgw awesome work on this fix! I've been trying to understand what it's doing and added a few tests to check the lockfile was updated correctly.

Let me know if this makes sense and is helpful!

Also fyi, pushed a fix for the failing spec in the `release-next` branch: https://github.com/npm/cli/pull/88

2018-10-29 15:33 UTC, larsgw requested changes
Thanks for the tests, that side of the behaviour is definitely important, especially now that that's the biggest problem it solves. Here's some feedback (first time using the review tool!).

2018-10-29 15:33 UTC, larsgw commented on test/tap/install-dep-classification.js
> +      t.similar(JSON.parse(fs.readFileSync(path.join(optionalDir, 'package-lock.json'), 'utf8')), {
This should be `devDir` right?

2018-10-29 15:33 UTC, larsgw commented on test/tap/install-dep-classification.js
> +            optional: true,
And these ones changed accordingly to `dev: true`.

2018-10-29 15:33 UTC, larsgw commented on test/tap/install-dep-classification.js
> +      t.similar(JSON.parse(fs.readFileSync(path.join(optionalDir, 'package-lock.json'), 'utf8')), {
This package lock also has `optional: true` on each dependency, did you omit those on purpose?

2018-10-29 15:33 UTC, larsgw commented on test/tap/install-dep-classification.js
> +      }, 'locks dependencies as optional')
And here too.

2018-10-29 16:29 UTC, feelepxyz commented
@larsgw nice one, thanks for the feedback! Pushed the fixes 👌

2018-10-30 15:08 UTC, larsgw approved these changes

2018-10-30 15:10 UTC, merged